# Generated by Django 5.1.7 on 2025-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobQuest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
