# Generated by Django 5.1.7 on 2025-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobQuest', '0005_profile_linkedin_profile_location_profile_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
